# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'
- task: SonarCloudPrepare@1
  displayName: 'Prepare Analysis Configuration'
  inputs:
    SonarCloud: 'Sonar Cloud Connection'
    organization: 'sachinkalia'
    scannerMode: 'MSBuild'
    projectKey: 'cosmosdbapp'
    projectName: 'cosmosdbapp'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Artifacts
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis on SonarCloud'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result on SonarCloud'
  inputs:
    pollingTimeoutSec: '300'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact to drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: AspNetCoreDrop
  condition: succeededOrFailed()
